<?php

/**
 * @file
 * PublicationNavigationServiceTest.php
 *
 * To run this test:
 * 
 * 1. From the DDEV project root:
 *    ddev ssh
 *    cd web
 * 
 * 2. Run all the tests:
 *    SIMPLETEST_DB=mysql://db:db@db/db ../vendor/bin/phpunit -c ./core/phpunit.xml.dist ./modules/custom/however_customizations/tests/
 * 
 * 3. To run just this specific test:
 *    SIMPLETEST_DB=mysql://db:db@db/db ../vendor/bin/phpunit -c ./core/phpunit.xml.dist ./modules/custom/however_customizations/tests/src/Kernel/PublicationNavigationServiceTest.php
 * 
 * Requirements:
 * - DDEV environment
 * - Drupal 10 with testing dependencies
 */

namespace Drupal\Tests\however_customizations\Kernel;

use Drupal\KernelTests\KernelTestBase;
use Drupal\node\Entity\Node;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\Entity\NodeType;

/**
 * Tests the PublicationNavigationService.
 *
 * @group however_customizations
 */
class PublicationNavigationServiceTest extends KernelTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'however_customizations',
    'node',
    'field',
    'text',
    'user',
    'system',
  ];

  /**
   * The navigation service.
   *
   * @var \Drupal\however_customizations\PublicationNavigationService
   */
  protected $navigationService;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();
    $this->installEntitySchema('node');
    $this->installEntitySchema('user');
    $this->installConfig(['system']);
    $this->navigationService = $this->container->get('however_customizations.publication_navigation');

    // Create however_volume content type
    NodeType::create([
      'type' => 'however_volume',
      'name' => 'However Volume',
    ])->save();

    // Create field storage for volume number
    FieldStorageConfig::create([
      'field_name' => 'field_volume_number',
      'entity_type' => 'node',
      'type' => 'integer',
    ])->save();

    // Create field instance
    FieldConfig::create([
      'field_name' => 'field_volume_number',
      'entity_type' => 'node',
      'bundle' => 'however_volume',
    ])->save();
  }

  /**
   * Test basic service instantiation.
   */
  public function testServiceExists() {
    $this->assertInstanceOf(
      'Drupal\however_customizations\PublicationNavigationService', 
      $this->navigationService
    );
  }

  /**
   * Test volume navigation for middle volume.
   * 
   * Validates that the navigation service can:
   * - Query database for nodes by bundle and volume number
   * - Access field_volume_number field values
   * - Return correct prev/next node objects
   * - Handle middle volume case (has both prev and next)
   */
  public function testVolumeNavigation()
  {
    // Create test volume nodes (titles auto-generated by hook_entity_presave)
    $volume1 = Node::create([
      'type' => 'however_volume',
      'field_volume_number' => 1,
      'status' => 1,
    ]);
    $volume1->save();

    $volume2 = Node::create([
      'type' => 'however_volume',
      'field_volume_number' => 2,
      'status' => 1,
    ]);
    $volume2->save();

    $volume3 = Node::create([
      'type' => 'however_volume',
      'field_volume_number' => 3,
      'status' => 1,
    ]);
    $volume3->save();

    // Test navigation service returns correct previous and next volumes
    $navigation = $this->navigationService->getVolumeNavigation($volume2);

    $this->assertEquals($volume1->id(), $navigation['prev']->id(), 'Previous volume should be volume 1');
    $this->assertEquals($volume3->id(), $navigation['next']->id(), 'Next volume should be volume 3');
    $this->assertEquals('How(ever) Volume 1', $navigation['prev']->getTitle(), 'Auto-generated title should be correct for previous volume');
    $this->assertEquals('How(ever) Volume 3', $navigation['next']->getTitle(), 'Auto-generated title should be correct for next volume');
  }
}
